docker_env: 
  description: "This is for nessie catalog"
  catalog_uri: "http://nessie:19120/api/v1"  # Nessie Server URI
  warehouse: "s3://warehouse/"               # Minio Address to Write to
  storage_uri: "http://172.22.0.3:9000"      # Minio IP address from docker inspect

database:
  finalytics:
    host: 
    port:
    username:
    password:
    database_name:
    driver:
    url:

