tables:
  nessie.raw.stock_eod_yfinance:
    schema:
    - name: date
      type: DateType
      nullable: false
    - name: open
      type: FloatType
      nullable: true
    - name: symbol
      type: StringType
      nullable: false
    - name: import_time
      type: TimestampType
      nullable: false