api: 
  yfinance_stock: ['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits']

tables:
  nessie.raw.stock_eod_yahoo:
    schema:
    - name: date
      type: DateType
      nullable: false
    - name: symbol
      type: StringType
      nullable: false
    - name: open
      type: StringType
      nullable: true
    - name: high
      type: StringType
      nullable: true
    - name: low
      type: StringType
      nullable: true
    - name: close
      type: StringType
      nullable: true
    - name: volume
      type: IntegerType
      nullable: true
    - name: import_time
      type: TimestampType
      nullable: false
    # partition_by:
    # # Optional partitioning
    # - field: date

  nessie.raw.etf_eod_yahoo:
    schema:
    - name: date
      type: DateType
      nullable: false
    - name: symbol
      type: StringType
      nullable: false
    - name: open
      type: FloatType
      nullable: true
    - name: high
      type: FloatType
      nullable: true
    - name: low
      type: FloatType
      nullable: true
    - name: close
      type: FloatType
      nullable: true
    - name: volume
      type: IntegerType
      nullable: true
    - name: import_time
      type: TimestampType
      nullable: false
    # partition_by:
    # # Optional partitioning
    # - field: date

  nessie.raw.etf_market_yahoo:
    schema:
    - name: symbol
      type: StringType
      nullable: false      
    - name: exchange_name
      type: StringType
      nullable: false      
    - name: market_state
      type: StringType
      nullable: true      
    - name: pre_market_time
      type: TimestampType
      nullable: true
    - name: pre_market_price
      type: FloatType
      nullable: true      
    - name: pre_market_change
      type: FloatType
      nullable: true      
    - name: pre_market_change_percent
      type: FloatType
      nullable: true
    - name: regular_market_time
      type: TimestampType
      nullable: true
    - name: regular_market_price
      type: FloatType
      nullable: true      
    - name: regular_market_change
      type: FloatType
      nullable: true      
    - name: regular_market_change_percent
      type: FloatType
      nullable: true
    - name: post_market_time
      type: TimestampType
      nullable: true
    - name: post_market_price
      type: FloatType
      nullable: true      
    - name: post_market_change
      type: FloatType
      nullable: true      
    - name: post_market_change_percent
      type: FloatType
      nullable: true      
    - name: import_time
      type: TimestampType
      nullable: false


  nessie.raw.stock_market_yahoo:
    schema:
    - name: symbol
      type: StringType
      nullable: false      
    - name: exchange_name
      type: StringType
      nullable: false      
    - name: market_state
      type: StringType
      nullable: true      
    - name: pre_market_time
      type: StringType
      nullable: true
    - name: pre_market_price
      type: FloatType
      nullable: true      
    - name: pre_market_change
      type: FloatType
      nullable: true      
    - name: pre_market_change_percent
      type: FloatType
      nullable: true
    - name: regular_market_time
      type: StringType
      nullable: true
    - name: regular_market_price
      type: FloatType
      nullable: true      
    - name: regular_market_change
      type: FloatType
      nullable: true      
    - name: regular_market_change_percent
      type: FloatType
      nullable: true
    - name: post_market_time
      type: StringType
      nullable: true
    - name: post_market_price
      type: FloatType
      nullable: true      
    - name: post_market_change
      type: FloatType
      nullable: true      
    - name: post_market_change_percent
      type: FloatType
      nullable: true      
    - name: import_time
      type: TimestampType
      nullable: false

  nessie.raw.stock_profile_yahoo:
    schema:
      - name: symbol
        type: StringType
        nullable: false
      - name: industry
        type: StringType
        nullable: true
      - name: sector
        type: StringType
        nullable: true
      - name: enterprise_value
        type: DoubleType
        nullable: true
      - name: forward_pe
        type: DoubleType
        nullable: true
      - name: profit_margins
        type: DoubleType
        nullable: true
      - name: float_shares
        type: DoubleType
        nullable: true
      - name: shares_outstanding
        type: DoubleType
        nullable: true
      - name: shares_short
        type: DoubleType
        nullable: true
      - name: shares_short_prior_month
        type: DoubleType
        nullable: true
      - name: short_ratio
        type: DoubleType
        nullable: true
      - name: short_percent_of_float
        type: DoubleType
        nullable: true
      - name: beta
        type: DoubleType
        nullable: true
      - name: book_value
        type: DoubleType
        nullable: true
      - name: price_to_book
        type: DoubleType
        nullable: true
      - name: last_fiscal_year_end
        type: StringType
        nullable: true
      - name: next_fiscal_year_end
        type: StringType
        nullable: true
      - name: most_recent_quarter
        type: StringType
        nullable: true
      - name: earnings_quarterly_growth
        type: DoubleType
        nullable: true
      - name: net_income_to_common
        type: DoubleType
        nullable: true
      - name: trailing_eps
        type: DoubleType
        nullable: true
      - name: forward_eps
        type: DoubleType
        nullable: true
      - name: peg_ratio
        type: DoubleType
        nullable: true
      - name: last_split_factor
        type: StringType
        nullable: true
      - name: last_split_date
        type: StringType
        nullable: true
      - name: import_time
        type: TimestampType
        nullable: false
    











    